# This file is intended to be sourced from one of the bashdb test programs

sourced_fn() {
    name="fn2"
    echo "SOURCED FN LINENO $LINENO"

    # Print a stack trace
    declare -i n
    n=${#FUNCNAME[@]}
    for (( i=0 ; (( i < $n )) ; i++ )) ; do 
        local -i j=i+1
	[ $j -eq $n ] && j=i  # main()'s file is the same as the first caller
	local filename=${BASH_SOURCE[$j]##*/}
	echo "FUNCNAME[$i]: ${FUNCNAME[$i]} called from $filename" \
	     "at line ${BASH_LINENO[$i]}"
    done
}

echo "SOURCED LINENO $LINENO"
filename=${BASH_SOURCE[0]##*/}
echo "SOURCED BASH_SOURCE[0]" $filename
sourced_fn


#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
