#!/bin/sh
#$Id: run-all,v 1.1 2006/01/02 23:34:26 rockyb Exp $

if [ -z "$*" ] ; then
	TESTS=run-*
else 
	TESTS=$*
fi

PATH=.:$PATH	# just to get recho/zecho/printenv if not run via `make tests'
export PATH

# unset BASH_ENV only if it is set
[ "${BASH_ENV+set}" = "set" ] && unset BASH_ENV
# ditto for SHELLOPTS
#[ "${SHELLOPTS+set}" = "set" ] && unset SHELLOPTS

${THIS_SH} ./version

rm -f *.check

echo Any output from any test, unless otherwise noted, indicates a possible anomaly

for x in $TESTS
do
	case $x in
	$0|run-minimal|run-gprof)	;;
	*.orig|*~) ;;
	*)	echo $x ; sh $x ;;
	esac
done

exit 0
