#!/bin/sh
#$Id: run-interrupt,v 1.1 2006/10/03 08:55:08 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check_common

TEST_NAME=interrupt
TEST_FILE="$builddir/${TEST_NAME}.check"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE ${srcdir}/${TEST_NAME}.right

exit $?

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
