#!/bin/sh
#$Id: run-multi,v 1.2 2006/01/03 04:58:07 rockyb Exp $

# Reinstate brkpt3 when BASH_COMMAND works again.
# exit 77

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check_common

for SUBTEST in multi1 multi2 multi3 multi4 ; do
  TEST_FILE="${SUBTEST}.check"
  (cd $srcdir && ${THIS_SH} ${SUBTEST}.tests > $TEST_FILE 2>&1 < /dev/null)

  check_output $TEST_FILE ${srcdir}/${SUBTEST}.right 
  typeset -i rc=$?
  if (( rc != 0 )) ; then 
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
