#!/bin/sh
#$Id: run-subshell,v 1.2 2006/01/03 05:13:22 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check_common

tests=${@:-"subshell1 subshell2 subshell3"}

for SUBTEST in $tests; do
  echo "checking $SUBTEST..."
  TEST_FILE="${SUBTEST}.check"
  (cd $srcdir && ${THIS_SH} ${SUBTEST}.tests > $TEST_FILE 2>&1 < /dev/null)

  check_output $TEST_FILE ${srcdir}/${SUBTEST}.right
  typeset -i rc=$?
  if (( rc == 0 )) ; then 
    rm -f $TEST_FILE
  else
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
