#!/bin/sh
#$Id: run-sig,v 1.8 2007/02/03 11:55:22 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check_common

TEST_NAME='sig'
TEST_FILE="/tmp/${TEST_NAME}.check"
TEST2_FILE="/tmp/${TEST_NAME}.check2"
RIGHT_FILE="/tmp/${TEST_NAME}.right"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
sed -i -e 's/^sig.tests: line 11:[ ]*[0-9]* Killed[: 9]* /sig.tests: line 11: xxxx Killed /' $TEST_FILE >${RIGHT_FILE}
grep -v "bashdbeval" ${srcdir}/${TEST_NAME}.right | sed -e 's/^sig.tests: line 11:[ ]*[0-9]* Killed[: 9]* /sig.tests: line 11: xxxx Killed /'>${RIGHT_FILE}
grep -v "bashdbeval" ${TEST_FILE} | sed -e 's/^sig.tests: line 11:[ ]*[0-9]* Killed[: 9]* /sig.tests: line 11: xxxx Killed /' >${TEST2_FILE}

check_output $TEST_FILE ${srcdir}/${TEST_NAME}.right

check_output $TEST2_FILE ${RIGHT_FILE} && {
  rm -f $TEST_FILE
}

rc=$?
rm $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $rc

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
