set showcommand 1
print "Test step inside multi-statement lines and subshells..."
step 1
step 3
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
p "BASH_SUBSHELL $BASH_SUBSHELL"
step
H
p "BASH_SUBSHELL $BASH_SUBSHELL"
quit
