#!/bin/sh
# -*- shell-script -*-
#$Id: test-subshell,v 1.4 2008/08/19 13:53:08 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

. ${builddir}/check-common.sh

tests=${@:-"subshell1 subshell2 subshell3"}

for SUBTEST in $tests; do
  echo "checking $SUBTEST..."
  RIGHT_FILE="${top_srcdir}/test/data/${SUBTEST}.right"
  (cd $srcdir && ${THIS_SH} ${SUBTEST}.tests > $TEST_FILE 2>&1 < /dev/null)

  check_output $TEST_FILE ${srcdir}/data/${SUBTEST}.right
  rc=$?
  if test "$rc" -eq  0 ; then
    rm -f $TEST_FILE
  else
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
