#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-command,v 1.4 2008/08/09 16:13:04 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='command'

. ${builddir}/check-common.sh

TEST_FILE="$builddir/${TEST_NAME}.check"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
