#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-frame,v 1.5 2008/08/19 21:23:23 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='frame'

. ${builddir}/check-common.sh

debugged_script="$builddir/example/hanoi.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
