#!/bin/sh
# -*- shell-script -*-
#$Id: test-list,v 1.4 2008/08/10 00:54:15 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD

TEST_NAME='list'

. ${builddir}/check-common.sh

debugged_script="$srcdir/dbg-test1.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
