#!/bin/sh
# -*- shell-script -*-
#$Id: test-restart,v 1.4 2008/08/09 02:36:19 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='restart'
. ${builddir}/check-common.sh

debugged_script="restartbug.sh"

echo 'Skipping restart test for now'
exit 77

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
