#!/bin/sh
# -*- shell-script -*-
#$Id: test-setshow,v 1.3 2008/08/09 02:36:19 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='setshow'

. ${builddir}/check-common.sh

TEST_FILTERED_FILE="/tmp/${TEST_NAME}-filtered.check"
OUT1_NAME='setshow'
OUT1_FILE="/tmp/${OUT1_NAME}.check"
rm -f $OUT1_FILE 
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

# Different OS's handle ARGV differently, and "info args" may come out
# differently depending on that.
cat ${TEST_FILE} | sed -e "s:1 = ./dbg-test2.sh:1 = dbg-test2.sh:" \
| sed -e 's:record the command history is .*:record the command history is: ' \
> ${TEST_FILTERED_FILE}

check_output $TEST_FILTERED_FILE $RIGHT_FILE
rc=$?

if test $rc -eq  0 ; then
  exit $rc
fi

check_output $OUT1_FILE ${srcdir}/data/${OUT1_NAME}.right

# Return code tells testing mechanism whether passed or not.
exit $?
