#!/bin/sh
#$Id: test-brkpt1,v 1.2 2008/08/08 20:56:22 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

. ${srcdir}/check-common.sh

TEST_NAME='brkpt1'
TEST_FILE="${TEST_NAME}.check"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE ${TEST_NAME}.right

# Return code tells testing mechanism whether passed or not.
exit $?

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
