#!/bin/sh
#$Id: test-restart,v 1.3 2008/08/08 20:56:22 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check-common.sh

echo 'Skipping restart test for now'
exit 77
TEST_NAME='restart'
TEST_FILE="$builddir/${TEST_NAME}.check"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE ${srcdir}/${TEST_NAME}.right

# Return code tells testing mechanism whether passed or not.
exit $?

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
