#!/bin/sh
# -*- shell-script -*-
#$Id: test-settrace,v 1.3 2008/08/09 02:36:19 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='settrace'

. ${builddir}/check-common.sh

debugged_script=settrace.sh
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
