#!/bin/sh
# -*- shell-script -*-
#$Id: test-sig,v 1.3 2008/08/09 02:36:19 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='sig'

. ${builddir}/check-common.sh

TEST_FILE="/tmp/${TEST_NAME}.check"
TEST2_FILE="/tmp/${TEST_NAME}.check2"
RIGHT_FILE="/tmp/${TEST_NAME}.right"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
sed -i -e 's/^sig.tests: line 11:[ ]*[0-9]* Killed[: 9]* /sig.tests: line 11: xxxx Killed /' $TEST_FILE >${RIGHT_FILE}
grep -v "bashdbeval" ${srcdir}/data/${TEST_NAME}.right | sed -e 's/^sig.tests: line 11:[ ]*[0-9]* Killed[: 9]* /sig.tests: line 11: xxxx Killed /'>${RIGHT_FILE}
grep -v "bashdbeval" ${TEST_FILE} | sed -e 's/^sig.tests: line 11:[ ]*[0-9]* Killed[: 9]* /sig.tests: line 11: xxxx Killed /' >${TEST2_FILE}

check_output $TEST_FILE ${srcdir}/data/${TEST_NAME}.right

check_output $TEST2_FILE ${RIGHT_FILE} && {
  rm -f $TEST_FILE
}

rc=$?
rm $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $rc
