#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-interrupt,v 1.3 2008/08/09 16:13:04 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check-common.sh

TEST_NAME=interrupt
TEST_FILE="$builddir/${TEST_NAME}.check"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE ${srcdir}/${TEST_NAME}.right

exit $?
