#!/bin/sh
# -*- shell-script -*-
#$Id: test-trace,v 1.5 2008/08/19 13:53:08 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/..

. ${builddir}/check-common.sh

tests=${@:-"trace trace2"}

for SUBTEST in $tests ; do
  echo "checking $SUBTEST..."
  TEST_NAME=$SUBTEST
  TEST_FILE="${top_builddir}/test/${SUBTEST}.check"
  RIGHT_FILE="${top_srcdir}/test/data/${SUBTEST}.right"
  (cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
  check_output $TEST_FILE ${srcdir}/data/${TEST_NAME}.right
  rc=$?
  if test $rc -eq 0  ; then 
    rm -f $TEST_FILE
  else
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
