#!/bin/sh
# -*- shell-script -*-
#$Id: test-debug,v 1.3 2008/08/08 22:04:19 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check-common.sh

TEST_NAME='debug'
TEST_FILE="$builddir/${TEST_NAME}.check"
RIGHT_FILE="/tmp/${TEST_NAME}.right"
TEST_FILTERED_FILE="/tmp/${TEST_NAME}-filtered.check"

(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

grep -v '##2 main("-q", "-L",' ${srcdir}/data/${TEST_NAME}.right >${RIGHT_FILE}
grep -v '##2 main("-q", "-L",' ${TEST_FILE} >${TEST_FILTERED_FILE}

check_output $TEST_FILTERED_FILE ${RIGHT_FILE} && {
  rm -f $TEST_FILE
}

rc=$?
rm $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $rc
