#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-opts,v 1.6 2008/08/19 13:53:08 rockyb Exp $
# Test bash options.

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD

TEST_NAME='sopts'

. ${builddir}/check-common.sh

(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE $RIGHT_FILE
rc=$?

TEMP=$(getopt -o testing 2>&1 >/dev/null)
if [ 0 = $? ] ; then
  TEST_NAME='lopts'
  TEST_FILE="${top_builddir}/test/${TEST_NAME}.check"
  (cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
  
  check_output $TEST_FILE ${srcdir}/data/${TEST_NAME}.right
  ((0==rc)) && rc=$?
fi

# Return code tells testing mechanism whether passed or not.
exit $rc
