#!/bin/sh
# -*- shell-script -*-
#$Id: test-multi,v 1.3 2008/08/09 02:36:19 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

. ${builddir}/check-common.sh

debugged_script=multi.sh
for SUBTEST in multi1 multi2 multi3 multi4 ; do
  cmdfile=data/${SUBTEST}.cmd
  TEST_FILE="${builddir}/${SUBTEST}.check"
  RIGHT_FILE=${srcdir}/data/${SUBTEST}.right
  (cd $srcdir && \
      run_debugger $debugged_script "-B -q -L ${TOP_BUILDDIR}" $cmdfile 2>&1 >$TEST_FILE </dev/null)

  check_output $TEST_FILE $RIGHT_FILE
  rc=$?
  if test "$rc" -eq  0 ; then
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
