#!/bin/bash
# -*- shell-script -*-
#$Id: test-bug-args,v 1.4 2008/08/09 11:54:16 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='bug-args'

. ${builddir}/check-common.sh

debugged_script="${TOP_BUILDDIR}/test/bug-args.sh"

(cd $srcdir && \
  run_debugger $debugged_script > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
