#!/bin/sh
#$Id: test-trace,v 1.2 2008/08/08 20:56:22 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

if test -z "$builddir"  ; then
  builddir=`pwd`
fi

. ${builddir}/check-common.sh

tests=${@:-"trace trace2"}

for SUBTEST in $tests ; do
  echo "checking $SUBTEST..."
  TEST_NAME=$SUBTEST
  TEST_FILE="$builddir/${TEST_NAME}.check"
  (cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
  check_output $TEST_FILE ${srcdir}/${TEST_NAME}.right
  rc=$?
  if test $rc -eq 0  ; then 
    rm -f $TEST_FILE
  else
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0

#;;; Local Variables: ***
#;;; mode:shell-script ***
#;;; eval: (sh-set-shell "bash") ***
#;;; End: ***
