#!/bin/bash
# -*- shell-script -*-
#$Id: test-watch1,v 1.6 2008/08/19 21:23:23 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD
export srcdir builddir

TEST_NAME='watch1'
. ${builddir}/check-common.sh

debugged_script="$srcdir/example/dbg-test1.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)
grep -v '^Restarting with' $RIGHT_FILE >${RIGHT_FILTERED_FILE}
grep -v '^Restarting with' $TEST_FILE  >${TEST_FILTERED_FILE}

check_output $TEST_FILTERED_FILE ${RIGHT_FILTERED_FILE}
rc=$? 
if ((0 == rc)) ; then
  rm -f $TEST_FILE
  rm -f $RIGHT_FILTERED_FILE
fi

# Return code tells testing mechanism whether passed or not.
exit $rc
