#!/bin/sh
# -*- shell-script -*-
#$Id: test-brkpt1,v 1.3 2008/08/08 22:04:19 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=`pwd`
fi

TEST_NAME='brkpt1'

. ${srcdir}/check-common.sh

TEST_FILE="${TEST_NAME}.check"
(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
