#!/bin/sh
# -*- shell-script -*-
#$Id: test-bugIFS,v 1.2 2008/08/08 09:14:52 rockyb Exp $

if test -z "$srcdir"  ; then
  srcdir=$PWD
fi

if test -z "$builddir"  ; then
  builddir=$PWD
fi

TEST_NAME='bugIFS'

. ${builddir}/check_common

(cd $srcdir && ${THIS_SH} ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE ${RIGHT_FILE} && {
  rm -f $TEST_FILE
}

# Return code tells testing mechanism whether passed or not.
exit $?
