#!/bin/sh
# -*- shell-script -*-
#$Id: test-multi,v 1.4 2008/08/10 00:54:15 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/..

. ${builddir}/check-common.sh

debugged_script=multi.sh
for SUBTEST in multi1 multi2 multi3 multi4 ; do
  cmdfile=data/${SUBTEST}.cmd
  TEST_FILE="${builddir}/${SUBTEST}.check"
  RIGHT_FILE=${srcdir}/data/${SUBTEST}.right
  (cd $srcdir && \
      run_debugger $debugged_script "-B -q -L ${top_builddir}" $cmdfile 2>&1 >$TEST_FILE </dev/null)

  check_output $TEST_FILE $RIGHT_FILE
  rc=$?
  if test "$rc" -eq  0 ; then
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
