#!/bin/sh
# -*- shell-script -*-
#$Id: test-tbreak,v 1.3 2008/08/09 02:36:19 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='tbreak'
. ${builddir}/check-common.sh

TEST_FILE="$builddir/${TEST_NAME}.check"
debugged_script="dbg-test1.sh"
(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
