#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-bugIFS,v 1.5 2008/08/09 16:13:04 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD

TEST_NAME='bugIFS'

. ${builddir}/check-common.sh

debugged_script="${TOP_BUILDDIR}/test/bugIFS.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE ${RIGHT_FILE} && {
  rm -f $TEST_FILE
}

# Return code tells testing mechanism whether passed or not.
exit $?
