#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-command,v 1.1 2008/08/22 19:08:00 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/..

TEST_NAME='command'

. ${builddir}/../check-common.sh

debugged_script="$top_builddir/test/example/dbg-test1.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
