#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-interrupt,v 1.1 2008/08/22 19:08:03 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

. ${top_builddir}/test/check-common.sh

TEST_NAME=interrupt
TEST_FILE="$builddir/${TEST_NAME}.check"
(cd $srcdir && $SH ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE ${top_builddir}/test/data/${TEST_NAME}.right

exit $?
