#!/usr/local/bin/bash
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off
SH=/usr/local/bin/bash

[ -z "$builddir" ] && export builddir=$PWD

. ${builddir}/check-common.sh
debugged_script="$top_srcdir/test/example/sig.sh"

FILTERED_TEST_FILE="/tmp/${TEST_NAME}-filtered.check"
FILTERED_RIGHT_FILE="/tmp/${TEST_NAME}-filtered.right"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

/bin/grep -v '^sig.tests: line 12' $RIGHT_FILE>${FILTERED_RIGHT_FILE}
/bin/grep -v '^sig.tests: line 12' $TEST_FILE \
  | /bin/sed -e "s:in file \`sig.sh' at line [0-9][0-9]*:in file \`sig.sh' at line 55:" \
  | /bin/sed -e "s:in file \`eval.sh' at line [0-9][0-9]*:in file \`eval.sh' at line 55:" \
  | /bin/grep -v '^sig.tests: line 10:' | /bin/grep -v '^SIGPIPE' >${FILTERED_TEST_FILE}
check_output $FILTERED_TEST_FILE $FILTERED_RIGHT_FILE
rc=$?

((0 != rc)) && exit $rc
rm $FILTERED_RIGHT_FILE
rm $TEST_FILE

# Return code tells testing mechanism whether passed or not.
exit 0
