#!/bin/bash
# -*- shell-script -*-
# Test debugger short options.
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && export builddir=$PWD
. ${builddir}/check-common.sh

(cd $srcdir && $SH ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
check_output $TEST_FILE $RIGHT_FILE
exit $?
