#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-sig,v 1.3 2008/08/23 17:09:36 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

TEST_NAME='sig'

. ${top_builddir}/test/integration/check-common.sh

FILTERED_TEST_FILE="/tmp/${TEST_NAME}-filtered.check"
FILTERED_RIGHT_FILE="/tmp/${TEST_NAME}-filtered.right"
(cd $srcdir && $SH ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

grep -v '^sig.tests: line 12' $RIGHT_FILE >${FILTERED_RIGHT_FILE}
grep -v '^sig.tests: line 12' $TEST_FILE >${FILTERED_TEST_FILE}
check_output $FILTERED_TEST_FILE $FILTERED_RIGHT_FILE
rc=$?

((0 != rc)) && exit $rc
rm $FILTERED_RIGHT_FILE
rm $TEST_FILE

# Return code tells testing mechanism whether passed or not.
exit 0
