#!/bin/bash
# -*- shell-script -*-
#$Id: test-bugIFS,v 1.3 2008/08/27 14:02:50 rockyb Exp $
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh
run_test_check
