#!/usr/bin/env bash
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh

script=dbg-test1
tests=${@:-"brkpt1 brkpt2 brkpt3"}
for SUBTEST in $tests ; do
    echo running $SUBTEST
    [[ $SUBTEST == brkpt3 ]] && script=subshell
    run_test_check $script $SUBTEST
    rc=$?
    (( $rc != 0 )) && exit $rc
done

# Return code tells testing mechanism whether passed or not.
exit 0
