#!/bin/bash
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh

for SUBTEST in multi1 multi2 multi3 multi4 ; do
    run_test_check $TEST_NAME $SUBTEST
done

# Return code tells testing mechanism whether passed or not.
exit 0
