#!/bin/bash
# -*- shell-script -*-
#$Id: test-watch1,v 1.2 2008/08/23 16:56:21 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

TEST_NAME='watch1'
. ${top_builddir}/test/integration/check-common.sh

debugged_script="$top_srcdir/test/example/dbg-test1.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)
grep -v '^Restarting with' $RIGHT_FILE >${RIGHT_FILTERED_FILE}
grep -v '^Restarting with' $TEST_FILE  >${TEST_FILTERED_FILE}

check_output $TEST_FILTERED_FILE ${RIGHT_FILTERED_FILE}
rc=$? 
if ((0 == rc)) ; then
  rm -f $TEST_FILE
  rm -f $RIGHT_FILTERED_FILE
fi

# Return code tells testing mechanism whether passed or not.
exit $rc
