#!/usr/bin/env bash
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh

tests=${@:-"multi1 multi2 multi3 multi4"}
for SUBTEST in $tests ; do
    echo running $SUBTEST
    run_test_check $TEST_NAME $SUBTEST
    rc=$?
    (( rc != 0 )) && exit $rc
done

# Return code tells testing mechanism whether passed or not.
exit 0
