#!/usr/bin/env bash
# -*- shell-script -*-
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[[ -z "$builddir" ]] && export builddir=$PWD

. ${builddir}/check-common.sh

debugged_script="$top_srcdir/test/example/bug-loc.sh"

if ( pygmentize --version || pygmentize -V ) 2>/dev/null 1>/dev/null ; then
    run_debugger_opts="-B -q --no-init --highlight=light"
    run_test_check $TEST_NAME $TEST_NAME $debugged_script
else
    exit 77
fi
