#!/bin/sh
# -*- shell-script -*-
#$Id: test-subshell,v 1.1 2008/08/22 19:25:07 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

. ${top_builddir}/test/check-common.sh

tests=${@:-"subshell1 subshell2 subshell3"}

for SUBTEST in $tests; do
  echo "checking $SUBTEST..."
  RIGHT_FILE="${top_srcdir}/test/data/${SUBTEST}.right"
  (cd $srcdir && $SH ${SUBTEST}.tests > $TEST_FILE 2>&1 < /dev/null)

  check_output $TEST_FILE ${top_srcdir}/test/data/${SUBTEST}.right
  rc=$?
  if test "$rc" -eq  0 ; then
    rm -f $TEST_FILE
  else
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
