#!/bin/bash
# -*- shell-script -*-
TEST_NAME='file with spaces'

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh

if (( ${BASH_VERSINFO[0]} == 4 && ${BASH_VERSINFO[1]} >= 3 )) ; then
    echo "Skipping because we don't have filesystem quoting worked out yet."
    exit 77
fi

if [[ -f "$top_srcdir/test/example/file with spaces.sh" ]] ; then
    run_test_check
else
    echo "Skipping test due to autoconf problems"
    exit 77
fi
