#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-misc,v 1.1 2008/08/22 19:25:07 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

TEST_NAME='misc'

. ${top_builddir}/test/check-common.sh

OUT1_NAME='misc-output'
OUT1_FILE="/tmp/${OUT1_NAME}.check"
rm -f $OUT1_FILE 

debugged_script="$top_builddir/test/example/dbg-test2.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

# Different OS's handle ARGV differently, and "info args" may come out
# differently depending on that.
cat ${TEST_FILE} | sed -e "s:1 = .*/dbg-test2.sh:1 = ./example/dbg-test2.sh:" \
| sed -e 's:record the command history is .*:record the command history is: ' \
> ${TEST_FILTERED_FILE}

check_output $TEST_FILTERED_FILE $RIGHT_FILE
rc=$?

if test $rc -eq  0 ; then
  exit $rc
fi

check_output $OUT1_FILE ${srcdir}/data/${OUT1_NAME}.right

# Return code tells testing mechanism whether passed or not.
exit $?
