#!/usr/bin/env bash
# -*- shell-script -*-
# Test debugger short options.
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && export builddir=$PWD
. ${builddir}/check-common.sh

debugged_script="$top_srcdir/test/example/dbg-test1.sh"

(cd $srcdir && $SH ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)
grep -v '^(bashdb_cmd' $RIGHT_FILE >${RIGHT_FILTERED_FILE}
grep -v '^(bashdb_cmd' $TEST_FILE  >${TEST_FILTERED_FILE}
check_output $TEST_FILTERED_FILE ${RIGHT_FILTERED_FILE}
rc=$? 
if ((0 == rc)) ; then
  rm -f $TEST_FILE
  rm -f $RIGHT_FILTERED_FILE
fi
# Return code tells testing mechanism whether passed or not.
exit $rc
