#!/bin/sh
# -*- shell-script -*-
#$Id: test-subshell,v 1.3 2008/08/29 02:55:44 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

. ${top_builddir}/test/integration/check-common.sh

tests=${@:-"subshell1 subshell2 subshell3"}

for TEST_NAME in $tests; do
  echo "checking $TEST_NAME..."
  RIGHT_FILE="${top_srcdir}/test/data/${TEST_NAME}.right"
  TEST_FILE="${top_builddir}/test/${TEST_NAME}.check"
  (cd $srcdir && $SH ${TEST_NAME}.tests > $TEST_FILE 2>&1 < /dev/null)

  check_output $TEST_FILE ${top_srcdir}/test/data/${TEST_NAME}.right
  rc=$?
  if test "$rc" -eq  0 ; then
    rm -f $TEST_FILE
  else
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
