#!/bin/bash
# -*- shell-script -*-
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh
output=$(run_test_check 2>&1)
if [[ -z $output ]] ; then
    exit 0
else
    echo $output
    exit 1
fi

