#!/usr/bin/env bash
# -*- shell-script -*-
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off

[[ -z "$builddir" ]] && export builddir=$PWD

. ${builddir}/check-common.sh

debugged_script="$top_srcdir/test/example/fib.sh"

[[ -z "$builddir" ]] && builddir=$PWD
run_test_check $TEST_NAME $TEST_NAME $debugged_script
