#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-bug-args,v 1.2 2008/08/23 16:56:21 rockyb Exp $

[ -z "$srcdir" ] && srcdir=$PWD
[ -z "$builddir" ] && builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

TEST_NAME='bug-args'

. ${top_builddir}/test/integration/check-common.sh

debugged_script="${top_builddir}/test/example/bug-args.sh"

(cd $srcdir && \
  run_debugger $debugged_script > $TEST_FILE 2>&1 < /dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
