#!/bin/bash
# -*- shell-script -*-
t=${0##*/}; TEST_NAME=${t:5}   # basename $0 with 'test-' stripped off
[[ -z "$builddir" ]] && export builddir=$PWD
[[ -z "$top_srcdir" ]] && export top_srcdir=${PWD}/..

debugged_script="$top_srcdir/test/example/fib.sh"

[[ -z "$builddir" ]] && builddir=$PWD
. ${builddir}/check-common.sh
run_test_check $TEST_NAME $TEST_NAME $debugged_script
