#!/bin/sh
# -*- shell-script -*-
#$Id: test-multi,v 1.2 2008/08/23 16:56:21 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

. ${top_builddir}/test/integration/check-common.sh

debugged_script=multi.sh
for SUBTEST in multi1 multi2 multi3 multi4 ; do
  cmdfile=${top_builddir}/test/data/${SUBTEST}.cmd
  TEST_FILE="${top_builddir}/test/${SUBTEST}.check"
  RIGHT_FILE="${top_srcdir}/test/data/${SUBTEST}.right"
  (cd $srcdir && \
      run_debugger $debugged_script "-B -q -L ${top_builddir}" $cmdfile 2>&1 >$TEST_FILE </dev/null)

  check_output $TEST_FILE $RIGHT_FILE
  rc=$?
  if test "$rc" -eq  0 ; then
    exit $rc
  fi
done

# Return code tells testing mechanism whether passed or not.
exit 0
