#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-action,v 1.1 2008/08/22 19:25:06 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD

TEST_NAME='action'

. ${builddir}/../check-common.sh

debugged_script="$top_srcdir/test/example/dbg-test1.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

check_output $TEST_FILE $RIGHT_FILE

# Return code tells testing mechanism whether passed or not.
exit $?
