#!/bin/bash -f
# -*- shell-script -*-
#$Id: test-debug,v 1.1 2008/08/22 19:25:07 rockyb Exp $

[ -z "$srcdir" ] && export srcdir=$PWD
[ -z "$builddir" ] && export builddir=$PWD
[ -z "$top_builddir" ] && export top_builddir=$builddir/../..

TEST_NAME='debug'

. ${top_builddir}/test/check-common.sh

RIGHT_FILTERED_FILE="/tmp/${TEST_NAME}-filtered.right"
debugged_script="$top_builddir/test/example/debug.sh"

(cd $srcdir && run_debugger $debugged_script 2>&1 >$TEST_FILE </dev/null)

grep -v '##2 main("-q", "-L",' $RIGHT_FILE >${RIGHT_FILTERED_FILE}
grep -v '##2 main("-q", "-L",' $TEST_FILE  >${TEST_FILTERED_FILE}

check_output $TEST_FILTERED_FILE ${RIGHT_FILTERED_FILE}
rc=$? 
if ((0 == rc)) ; then
  rm -f $TEST_FILE
  rm -f $RIGHT_FILTERED_FILE
fi

# Return code tells testing mechanism whether passed or not.
exit $rc
