#!/usr/bin/env bash
# -*- shell-script -*-
TEST_NAME='file with spaces'

[ -z "$builddir" ] && builddir=$PWD
. ${builddir}/check-common.sh

if [[ -f "$top_srcdir/test/example/file with spaces.sh" ]] ; then
    run_test_check
else
    echo "Skipping test due to autoconf problems"
fi
